### ISSUE TITLE
Sorting column tables

### ISSUE THREAD

**Issue by bens29-mm** [mottmacdonaldglobal/Report-Tool#5]
As image list is sorted numerically (lowest to highest) there is potential for images to be mismatched to their comments when copy + pasted from a spreadsheet, for example where the image list in the spreadsheet is not sequential (eg. IMG_2145, IMG_2144, IMG_2146) the comments will not align with the correct image as the list will be re-sorted in numerical order. Is there perhaps a way to upload the photos in the order they are selected and not automatically list them numerically? In the example here, the images need to be presented in the report in the order shown in the spreadsheet so simply swapping the comments in the table is not an option. Without having to rename the image names to 'trick' the script into using the numerical order (which is not practical where there might be hundreds of images being uploaded and matched to comments) is there a possible way to ammend the order of the uploaded images in the list?

This is a specific issue to the method I have used to log defects in a spreadsheet with a description in an adjacent cell
![Mismatched Image Example](https://user-images.githubusercontent.com/89444240/141220540-f03236a7-ce2a-4c3f-94d8-7c690c273d93.PNG)
.

**Comment by sonomirco** [comment]
@bens29-mm 
this is a very interesting request because my first answer would be, sort the excel file by photo No. and you will have the same order of the table 🤣, BUT I think there is something more behind here!!
So I think the order is driven by where the pictures are taken, isn't it? Is this order important also in the report?
Maybe we could talk about the process of capturing?

**Comment by bens29-mm** [comment]
@sonomirco 
yes agreed this is quite a specific request. in the example above our order is important to the report so the order data is captured in our inspections is the order in which it needs to show in the report. for efficiency this order cannot be changed on site, the intention of this script originally was such that we would be able to reduce time spent on site and the script would handle which ever order we collected the information in based on the spreadsheet list. that is to say, unfortunately sorting the excel file by photo number won;t be suitable.

**Comment by sonomirco** [comment]
Sorting to the column will be added.
